CREATE TABLE `metadata` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `metadata_cn_name` varchar(255) NOT NULL COMMENT '元数据中文名称',
  `metadata_en_name` varchar(255) NOT NULL COMMENT '元数据英文名称',
  `metadata_cn_meaning` varchar(500) NOT NULL COMMENT '元数据中文含义',
  `metadata_en_meaning` varchar(500) NOT NULL COMMENT '元数据英文含义',
  `java_field_name` varchar(255) NOT NULL COMMENT 'Java代码中的英文名称',
  `db_field_name` varchar(255) NOT NULL COMMENT '数据库表中的字段名称',
  `java_data_type` varchar(100) NOT NULL COMMENT 'Java数据类型',
  `mysql_data_type` varchar(100) NOT NULL COMMENT 'MySQL数据类型',
  `max_length` int(11) NOT NULL COMMENT '最大长度',
  `min_length` int(11) NOT NULL DEFAULT '0' COMMENT '最小长度',
  `value_range` varchar(500) DEFAULT NULL COMMENT '取值范围（正则表达式）',
  `business_desc` text NOT NULL COMMENT '业务描述',
  `business_domain` varchar(255) NOT NULL COMMENT '所属业务域',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '录入时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  `status` char(1) NOT NULL DEFAULT '1' COMMENT '生效状态（1：生效，0：失效）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_metadata_cn_name_domain_status` (`metadata_cn_name`, `business_domain`, `status`),
  UNIQUE KEY `uk_metadata_en_name_domain_status` (`metadata_en_name`, `business_domain`, `status`),
  KEY `idx_java_field_name` (`java_field_name`),
  KEY `idx_db_field_name` (`db_field_name`),
  KEY `idx_java_data_type` (`java_data_type`),
  KEY `idx_business_domain` (`business_domain`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='元数据管理表';