CREATE TABLE `metadata` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `metadata_chinese_name` varchar(255) NOT NULL COMMENT '元数据中文名称',
  `metadata_english_name` varchar(255) NOT NULL COMMENT '元数据英文名称',
  `metadata_chinese_meaning` varchar(255) NOT NULL COMMENT '元数据中文含义',
  `metadata_english_meaning` varchar(255) NOT NULL COMMENT '元数据英文含义',
  `java_field_name` varchar(255) NOT NULL COMMENT 'Java代码中的英文名称',
  `database_field_name` varchar(255) NOT NULL COMMENT '数据库表中的字段名称',
  `java_data_type` varchar(50) NOT NULL COMMENT 'Java代码中的数据类型',
  `mysql_data_type` varchar(50) NOT NULL COMMENT 'MySQL中的数据类型',
  `max_length` int(11) NOT NULL COMMENT '元数据的最大长度',
  `min_length` int(11) NOT NULL DEFAULT '0' COMMENT '元数据的最小长度',
  `value_range` varchar(255) DEFAULT NULL COMMENT '元数据取值范围（正则表达式）',
  `business_description` varchar(500) NOT NULL COMMENT '元数据的业务描述',
  `business_domain` varchar(100) NOT NULL COMMENT '元数据所属业务域',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '元数据的录入时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '元数据的最后修改时间',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '元数据生效状态（1：生效，0：失效）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_metadata_chinese_name_business_domain` (`metadata_chinese_name`,`business_domain`),
  UNIQUE KEY `uk_metadata_english_name_business_domain` (`metadata_english_name`,`business_domain`),
  UNIQUE KEY `uk_java_field_name_business_domain` (`java_field_name`,`business_domain`),
  UNIQUE KEY `uk_database_field_name_business_domain` (`database_field_name`,`business_domain`),
  KEY `idx_java_data_type` (`java_data_type`),
  KEY `idx_mysql_data_type` (`mysql_data_type`),
  KEY `idx_business_domain` (`business_domain`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='元数据管理表';